# Generated by Haxe 3.4.7
# coding: utf-8



class CST:
    __slots__ = ()

    def __init__(self):
        pass


class Common:
    __slots__ = ()

    @staticmethod
    def main():
        pass


CST.MESSAGE = 0
CST.CONNECTION = 1
CST.DOT_COLOR = 2
CST.RANKING = 3
CST.MAP = 4
CST.DISCONNECTION = 5
CST.UPDATE = 6
CST.TOWER = 7
CST.FULL = 8
CST.WIN = 9
CST.PILLAR = 10
CST.PILLAR_ATTACK = 11
CST.SIZE = 27
CST.DOT_COST = 1
CST.DOT_REGEN = 3
CST.SECTOR_COST = 25
CST.ENERGY_DEFAULT = 100
CST.WIN_DOTS = 10

Common.main()