# Generated by Haxe 3.4.7
# coding: utf-8



class ServerHelpers:
    __slots__ = ()

    @staticmethod
    def main():
        pass


class Hello:
    __slots__ = ()

    def __init__(self):
        print("i'm the real hello")



ServerHelpers.main()